name: Grading Report
on:
  - workflow_dispatch
  - push
  # - pull_request

permissions:
  checks: write
  actions: read
  contents: read
  pull-requests: write

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grade Report
        uses: ./ # Uses an action in the root directory
        env:
          MAX_POINTS: 50
